services:
  web:
    build: .
    container_name: family_hub
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
      - ./data:/code/data
    environment:
      - DATABASE_URL=sqlite:///./data/family_hub.db
      # Immich settings are referenced from the '.env' file
      - IMMICH_API_URL=${IMMICH_URL}
      - IMMICH_API_KEY=${IMMICH_API_KEY}
      # These will be used later
      - IMMICH_UPLOAD_ALBUM=test
      - IMMICH_SHOWCASE_ALBUM=test2
    restart: always
